name: Deploy Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:
  repository_dispatch:
    types: [docs-update]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docs repository
        uses: actions/checkout@v4

      - name: Checkout monorepo
        uses: actions/checkout@v4
        with:
          repository: tafystudio/tafystudio
          path: tafystudio-main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Make scripts executable
        run: chmod +x .github/scripts/*.sh

      - name: Extract documentation
        run: .github/scripts/extract-docs.sh

      - name: Prepare documentation
        run: .github/scripts/prepare-docs.sh

      - name: Build Docusaurus
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4