name: Update Documentation

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to pull documentation from'
        required: false
        default: 'main'
  repository_dispatch:
    types: [docs-update]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout documentation repository
        uses: actions/checkout@v4
        
      - name: Checkout monorepo
        uses: actions/checkout@v4
        with:
          repository: tafystudio/tafystudio
          path: monorepo
          ref: ${{ github.event.inputs.branch || 'main' }}
          token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
          
      - name: Update documentation
        run: |
          # Copy documentation from monorepo
          if [ -d "monorepo" ]; then
            echo "Monorepo found, checking for documentation..."
            if [ -d "monorepo/docs" ]; then
              echo "Documentation directory found in monorepo"
              # Clear existing docs except intro.md
              find docs -type f -name "*.md" ! -name "intro.md" -delete || true
              
              # Copy new documentation
              cp -r monorepo/docs/* docs/ || true
              
              # Check if there are changes
              if [ -n "$(git status --porcelain)" ]; then
                echo "Documentation changes detected"
                echo "HAS_CHANGES=true" >> $GITHUB_ENV
              else
                echo "No documentation changes"
                echo "HAS_CHANGES=false" >> $GITHUB_ENV
              fi
            else
              echo "No docs directory found in monorepo"
              echo "HAS_CHANGES=false" >> $GITHUB_ENV
            fi
          else
            echo "Monorepo not found, cannot update documentation"
            echo "HAS_CHANGES=false" >> $GITHUB_ENV
          fi
          
      - name: Create Pull Request
        if: env.HAS_CHANGES == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'docs: update documentation from monorepo'
          title: 'Update documentation from monorepo'
          body: |
            This PR updates the documentation from the monorepo.
            
            - Source branch: ${{ github.event.inputs.branch || 'main' }}
            - Triggered by: ${{ github.event_name }}
          branch: update-docs-${{ github.run_number }}
          delete-branch: true